# Generated by Django 4.2.7 on 2023-11-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_dob', models.DateField(max_length=20)),
                ('client_email', models.CharField(max_length=200)),
                ('client_country', models.CharField(choices=[('FR', 'Unites States of America'), ('DE', 'Germany'), ('CA', 'Canada'), ('SR', 'Senior'), ('GR', 'Graduate'), ('OT', 'Other')], default='OT', max_length=2)),
            ],
        ),
    ]
