# Generated by Django 4.2.7 on 2023-11-10 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '    Inclusions',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '     Photos',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '  Pricing',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': ' Properties',
            },
        ),
        migrations.CreateModel(
            name='Room_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '   Room Types',
            },
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_title', models.CharField(max_length=200)),
                ('tour_code', models.CharField(max_length=200)),
                ('tour_days', models.CharField(max_length=200)),
                ('group_type', models.CharField(choices=[('GP', 'Group'), ('BT', 'Both'), ('PR', 'Private')], default='PR', max_length=2)),
                ('guide_type', models.CharField(choices=[('PG', 'Partially Guided'), ('SG', 'Self Guided'), ('FG', 'Fully Guided')], default='FG', max_length=2)),
                ('website_link', models.CharField(blank=True, max_length=200, null=True)),
                ('single_supplement', models.CharField(choices=[('NO', 'No Single Supplement'), ('YE', 'Mandatory Single Supplement')], default='NO', max_length=2)),
                ('instant_bookability', models.CharField(choices=[('NO', 'No Instant Bookingt'), ('YE', 'Instant Booking')], default='YE', max_length=2)),
                ('physical_rating', models.CharField(choices=[('RE', 'Relaxing'), ('EA', 'Easy'), ('MO', 'Moderate'), ('SE', 'Serious'), ('HP', 'Heart pumping')], default='SE', max_length=2)),
                ('introduction', models.TextField(blank=True, max_length=1200, null=True)),
                ('added_date', models.DateField(blank=True, null=True, verbose_name='Added date')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
            options={
                'verbose_name_plural': '       Overview',
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_point', models.CharField(blank=True, max_length=200, null=True)),
                ('ending_point', models.CharField(blank=True, max_length=200, null=True)),
                ('detailed_itinerary', models.TextField(blank=True, max_length=20200, null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.overview')),
            ],
            options={
                'verbose_name_plural': '      Itineraries',
            },
        ),
    ]
