# Generated by Django 4.2.7 on 2023-11-09 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touroverview',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Operator',
        ),
    ]
