# Generated by Django 4.2.7 on 2023-11-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_alter_touroverview_operator_delete_choice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inclusion',
            options={'verbose_name_plural': '    Inclusions'},
        ),
        migrations.AlterModelOptions(
            name='itinerary',
            options={'verbose_name_plural': '      Itineraries'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name_plural': '     Photos'},
        ),
        migrations.AlterModelOptions(
            name='pricing',
            options={'verbose_name_plural': '  Pricing'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': ' Properties'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name_plural': '   Room Types'},
        ),
        migrations.AlterModelOptions(
            name='touroverview',
            options={'verbose_name_plural': '       Overview'},
        ),
    ]
