# Generated by Django 4.2.7 on 2023-11-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('tour', '0003_alter_inclusion_options_alter_itinerary_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TourOverview',
            new_name='Overview',
        ),
        migrations.RenameModel(
            old_name='RoomType',
            new_name='Room_Type',
        ),
    ]
