# Generated by Django 4.2.7 on 2023-11-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_rename_touroverview_overview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overview',
            old_name='country',
            new_name='tour_code',
        ),
        migrations.RenameField(
            model_name='overview',
            old_name='email',
            new_name='tour_days',
        ),
        migrations.RenameField(
            model_name='overview',
            old_name='phone2',
            new_name='website_link',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='category',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='n_type',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='price',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='website',
        ),
        migrations.AddField(
            model_name='overview',
            name='group_type',
            field=models.CharField(choices=[('GP', 'Group'), ('BT', 'Both'), ('PR', 'Private')], default='PR', max_length=2),
        ),
        migrations.AddField(
            model_name='overview',
            name='guide_type',
            field=models.CharField(choices=[('PG', 'Partially Guided'), ('SG', 'Self Guided'), ('FG', 'Fully Guided')], default='FG', max_length=2),
        ),
        migrations.AddField(
            model_name='overview',
            name='instant_bookability',
            field=models.CharField(choices=[('NO', 'No Instant Bookingt'), ('YE', 'Instant Booking')], default='YE', max_length=2),
        ),
        migrations.AddField(
            model_name='overview',
            name='introduction',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='physical_rating',
            field=models.CharField(choices=[('RE', 'Relaxing'), ('EA', 'Easy'), ('MO', 'Moderate'), ('SE', 'Serious'), ('HP', 'Heart pumping')], default='SE', max_length=2),
        ),
        migrations.AddField(
            model_name='overview',
            name='single_supplement',
            field=models.CharField(choices=[('NO', 'No Single Supplement'), ('YE', 'Mandatory Single Supplement')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='overview',
            name='added_date',
            field=models.DateField(blank=True, null=True, verbose_name='Added date'),
        ),
    ]
