# Generated by Django 4.2.7 on 2023-11-09 14:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BookingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_dob', models.DateField(max_length=20)),
                ('client_country', models.CharField(max_length=100)),
                ('client_email', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('budget', models.CharField(max_length=200)),
                ('pax', models.CharField(max_length=10)),
                ('safari_title', models.CharField(max_length=200)),
                ('inquiry_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='date published')),
                ('departure_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='date departing')),
                ('description', models.TextField(max_length=5000)),
                ('comments', models.TextField(max_length=5000)),
                ('medical_restriction', models.TextField(max_length=1000)),
                ('starting_point', models.CharField(max_length=200)),
                ('assigned_guides', models.CharField(max_length=200)),
                ('ending_point', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('consultant', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_amount', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('due_date', models.DateTimeField(null=True, verbose_name='date published')),
                ('booking_status', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.bookingstatus')),
                ('booking_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingtype')),
            ],
        ),
    ]
