# Generated by Django 4.2.7 on 2023-11-09 17:36

import booking.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('client', '0002_client_pub_date'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='client_country',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='client_dob',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='client_phone',
        ),
        migrations.AddField(
            model_name='booking',
            name='operator_name',
            field=models.ForeignKey(default=datetime.datetime(2023, 11, 9, 17, 36, 56, 984666, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_name',
            field=models.ForeignKey(default=booking.models.Booking.get_last, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Departing on'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='inquiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Inquired on'),
        ),
    ]
