# Generated by Django 4.2.7 on 2023-11-09 15:16

import booking.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='client_country',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='client_dob',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='client_phone',
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_name',
            field=models.ForeignKey(default=booking.models.Booking.get_last, on_delete=django.db.models.deletion.SET_DEFAULT, to='client.client'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Departing on'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='inquiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Inquired on'),
        ),
    ]
