# Generated by Django 4.2.7 on 2023-11-09 15:45

import booking.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_pub_date'),
        ('booking', '0002_remove_booking_client_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='client_name',
            field=models.ForeignKey(default=booking.models.Booking.get_last, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
